import streamlit as st

st.set_page_config(
    page_title="DDI-GPT",
    page_icon=":material/prescriptions:",
)

st.write("## Welcome to DDI-GPT web server for knowledge-enhanced DDI exploration")

st.sidebar.success("Select a page above.")

st.markdown(
    """
   ---
#### Visualize interactions 
DDI-GPT web server allows users to visualize various drug-protein-drug interaction networks and drug-side-effects-drug interaction network.\
The user can view shortest paths or two-hop paths between the combination of drugs. 
#### Submit a job
DI-GPT web server allows users to explore the predictions that were made by DDI-GPT framework. \
The user submits a pair of drugs, referenced by DrugBank ID, the input sentence is generated by incorporating drug-related biomedical entities from KG. \
The input is then set to a cluster running the prediction pipeline, where it is processed. \
Once the interface prediction is complete, the DDI-GPT web server will be updated to visualize importance words generated by explanation module,\
\n\n
 **👈 Select a page from the sidebar** to see some examples

---

#### Model architecture 

"""
)
st.image("html_files/Picture1.png")